initial trial of log ingesting to es (#8)
* initial trial of log ingesting to es
* adding tests to the log extractor lambda; restructuring to facilitate this
* updating readme file to reflect changes to repository strucutre
* updating travis script to implement auto builds
* adding environment check to es credentials
* removing aws auth when environment is test
* removing test values from function

diff --git a/scripts/install_script b/scripts/install_script
--- a/scripts/install_script
+++ b/scripts/install_script
@@ -4,14 +4,20 @@ SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 LAMBDA_NAME="$1"
 
 pushd `pwd -P`
-cd $SCRIPT_DIR/../lambda_functions
+cd $SCRIPT_DIR/..
 
-if [[ ! -f "$LAMBDA_NAME"/requirements.txt ]]; then
-    echo "Unable to find requirements.txt for '$LAMBDA_NAME'"
-    popd
-    exit 1
-fi
+case $LAMBDA_NAME in
+    all)
+        find . -name "requirements.txt" | sort -r | sed -e 's/^/-r /' | xargs python3 -m pip install ;;
+    *)
+        if [[ ! -f "./lambda_functions/$LAMBDA_NAME"/requirements.txt ]]; then
+            echo "Unable to find requirements.txt for '$LAMBDA_NAME'"
+            popd
+            exit 1
+        fi
 
-pip install --upgrade -r "$LAMBDA_NAME"/requirements.txt
+        python3 -m pip install --upgrade -r "./lambda_functions/$LAMBDA_NAME"/requirements.txt;;
+esac
+
 popd
 exit 0
